Mobile version skeleton
piero-vic/Portfolio pull request #1
Opened 2021-09-15 21:43 UTC by piero-vic

# Mobile version skeleton
The skeleton includes:
- Toolbar (or header)
- Headline section (or hero section)

2021-09-15 22:25 UTC, barackm requested changes
Hi @piero-vic, 👋 

You have done an amazing job so far! 👏👏👏
However, there are some issues that you still need to work on to go to the next project. But remember you are almost there 😉  😉 !

### To Highlight
✔️  Good commit messages
✔️  Good PR title
✔️  Good use of GitHub flow 👏 

# STATUS: Required Changes ♻️
### _Check the comments under the review._ 👇 
![](https://media.giphy.com/media/iZKF7CKpEEva2OZE6a/giphy.gif)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-15 22:25 UTC, barackm commented on index.html
> +    </header>
- [ ] Kindly let's use an anchor `<a>` tag for the logo(John Doe) since it's supposed to be clickable, this will keep our code more semantic.
- [ ] Let's also use the `<nav>` tag instead of the `<div class="button-container">`, and remember the hamburger is something we can click on to show the hidden menu links, this means we should have the `<img src="assets/hamburger.svg" alt="">` inside of either a `<button>` or an anchor `<a>` 👍

2021-09-15 22:25 UTC, barackm commented on index.html
> +      </div>
- [ ] Kindly let's have the social media icons inside a list element since we actually have a list of links that are grouped together, this is going to help us keep the code clean and more semantic, see the example below 👇 
```
<ul>
   <li>
      <a href="URL to your social media profile"><img class="icon" src="assets/Github.svg" alt=""></a>
   </li>
   <li>
      <a href="URL to your social media profile"><img class="icon" src="assets/Linkedin.svg" alt=""></a>
   </li>
</ul>
```
Kindly let's fix this issue 😉

2021-09-15 22:25 UTC, barackm commented on index.html
> +    <main class="hero">
- [ ] I think we should use a `<section>` tag as the container for the headline section, using `<main>` isn't going to be semantic, since the main tag is used to wrap all the content of the web page and not individual sections 👍

2021-09-15 22:25 UTC, barackm commented on style.css
> +  display: flex;
- [ ] This is great using flexbox to layout your content, congrats 👏 , But we can still improve this code by using DRY (don't repeat yourself) but why? well, I realized that you have used the property `display: flex` at multiple places, please let's keep the code clean by extracting the property into a separate class that can be reused at multiple places, see the example below: 

- CSS file
```
.d-flex {
  display: flex;
}

.flex-center {
  align-items: center;
  justify-content: center;
}
```
- HTML file
```
<div class="d-flex flex-center">{your content}</div>
```

And remember you can do this for all the other properties that seem to be repeated multiple times like the `font-family`, With this, I promise you'll be coding like a pro 😉

2021-09-15 22:25 UTC, barackm commented on README.md
> +> Porfolio Webpage
- [ ] [OPTIONAL] I think it could be a good idea to give a better description of the project, telling what is the project all about, what it contains...
- [ ] Kindly let's add instructions on how to set up the project locally so that non-technical people can have an idea on how to do so 😉

2021-09-15 22:25 UTC, barackm commented on README.md
> +This project is [MIT](./MIT.md) licensed.
- [ ] Please remember to update the path to the license file, because this link is broken 👍

2021-09-16 02:36 UTC, mke2111 approved these changes
### Hi @piero-vic, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
**Congratulations! 🎉** 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-16 02:37 UTC, merged