Mobile version implementation
piero-vic/Portfolio pull request #2
Opened 2021-09-16 22:01 UTC by piero-vic

# Mobile version implementation
- "My Recent Works" Section
    - Contains multiple card templates

- "About me" Section

- "Skills" Section
    - Conteins a list of languages, frameworks and skills

2021-09-16 22:34 UTC, ZeenatLawal requested changes
Hi @piero-vic, 

Great job so far!:clap: :clap:
## To Highlight 🎊 🎊 
- GitHub flow is followed. ✔️
- PR has a title and summary. ✔️

There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-16 22:34 UTC, ZeenatLawal commented on index.html
> +    </section>
- [ ] The See Project buttons in this section should follow the button styling: Active, Hover and Pressed (see design)

2021-09-16 22:34 UTC, ZeenatLawal commented on index.html
> +      </div>
- [ ]  There seems to be an overflow on the page caused by this section, kindly fix it.
![Screenshot (268)](https://user-images.githubusercontent.com/46851023/133692781-9814b136-6387-4aa3-9021-2bda75ca5363.png)

2021-09-16 22:34 UTC, ZeenatLawal commented on index.html
> +    </section>
- [ ] Kindly make sure this section has similar margins (top, bottom, left, right) as defined in the design

2021-09-16 22:34 UTC, ZeenatLawal commented on style.css
> +}
- [ ]  Kindly make sure this section uses the same background colour (#fff or white) as defined in the design

2021-09-16 22:34 UTC, ZeenatLawal commented on style.css
> +}
- [ ]  I think it'll be good to adjust the position of this background image so the text above it in this section will be readable.

2021-09-16 22:34 UTC, ZeenatLawal commented on index.html
> +      </button>
- [ ] The Get My Resume button should follow the button styling: Active, Hover and Pressed (see design)

2021-09-17 07:01 UTC, piero-vic commented on index.html
> +      </button>
Hi.I think the buttons work propperly

2021-09-17 07:06 UTC, piero-vic commented on index.html
> +      </button>
Hi. Thanks for all the feedbak.
I think the buttons work properly. I got some strange behavior when the mobile device mode on developer tools is used. If you happen to know why this may be happening please point me in the right direction.
Thank you again.

2021-09-17 16:44 UTC, ZeenatLawal approved these changes
Hi @piero-vic, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

## Congratulations! 🎉 
![6vEo](https://user-images.githubusercontent.com/46851023/133564373-95c66227-e33a-4506-b21a-d6db9b3a2050.gif)

## Optional suggestions
You can also consider:
  - Changing the title of the portfolio (I'm Alex) to your own name as this is your portfolio :smile:

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2021-09-17 16:47 UTC, ZeenatLawal commented on index.html
> +      </button>
- This happens when the responsiveness is turned on, I forgot to turn it off while checking the buttons, my apologies for that.:smile:

2021-09-17 17:02 UTC, piero-vic commented on index.html
> +      </button>
Don't worry. Thanks for all the feedback. It was really helpful.

2021-09-17 17:02 UTC, merged