Desktop version
piero-vic/Portfolio pull request #6
Opened 2021-09-23 21:35 UTC by piero-vic

# Desktop Version
- Adapt to desktop version.
- Add navigation links.
- Refactor code.

2021-09-23 22:47 UTC, Alexoid1 requested changes
Hi @piero-vic,

Impressive project!
You are doing a great job so far, and the project is looking good.

## Required Changes :recycle:
- For the project to get approved implement the changes mentioned below.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2021-09-23 22:47 UTC, Alexoid1 commented on style.css
>  .card {
- [ ] Kindly make the description and dark opacity in the background disappears on `hover` the element.
- [ ] The button `See project` just appears when the user hovers over the element.
![Captura de pantalla_2021-09-23_17-33-46](https://user-images.githubusercontent.com/53111464/134592739-915840d4-e045-471e-8806-7e44e5b319a7.png)

2021-09-23 22:47 UTC, Alexoid1 commented on index.html
> +    <section class="padding-section d-flex dark-section hero-section">
![Captura de pantalla_2021-09-23_17-38-17](https://user-images.githubusercontent.com/53111464/134593179-492374f2-a3bc-4b60-8639-a0d7ad7f0aea.png)
- [ OPTIONAL] This is how your project looks with the zoom value at 25% you can easily fix it by adding a max-width property to the project container and then align it to the center.

2021-09-24 01:43 UTC, TedLivist approved these changes
## STATUS: APPROVED ✔️ ✔️ 

Hi @piero-vic,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-24 02:06 UTC, merged